**Dados 02**
=========================

## Normalizando e transformando dados

**Grahcyanne's:** Geovana Bettero e Samira Oliveira

---

Nessa análise dos dados, iremos utilizar um dos DataFrames presente na biblioteca `seaborn`, que informa sobre 10 atributos a respeito de diamantes.<br>
São eles:<br>
Preço - em dólares americanos (326 - 18,823)<br>
Quilate - peso do diamante (0,2--5,01)<br>
Corte - qualidade do corte (Regular, Bom, Muito Bom, Premium, Ideal)<br>
Cor - cor do diamante, de D (melhor) a J (pior)<br>
Clareza - quão claro é o diamante (I1 (pior), SI2, SI1, VS2, VS1, VVS2, VVS1, IF (melhor))<br>
X - comprimento em mm (0--10,74)<br>
Y - largura em mm (0--58,9)<br>
Z - profundidade em mm (0--31,8)<br>
Profundidade - porcentagem de profundidade total = z / média (x, y) = 2 * z / (x + y) (43--79)<br>
Mesa - largura do topo do losango em relação ao ponto mais largo (43 - 95)<br><br>

Playlist deste notebook: https://youtu.be/fP5MxbZ5Df0<br>

In [1]:
import seaborn as sns
import pandas as pd

dataframe = sns.load_dataset("diamonds")
dataframe

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

<h4>Analisando os tipos de dados:</h4>

In [2]:
print(dataframe.dtypes)

carat       float64
cut        category
color      category
clarity    category
depth       float64
table       float64
price         int64
x           float64
y           float64
z           float64
dtype: object

Cópia de segurança do Data frame antes de realizar as transformações:

<h2>Transformações</h2>
<h4>Transformando dólar para real:</h4>

`Atenção!` essa transformação obedece a cotação do dólar do dia 15/08/2023

In [3]:
dataframe2 = dataframe.copy()

In [4]:
dataframe2["price"] = dataframe2["price"] * 4.99
dataframe2

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.23,Ideal,E,SI2,61.5,55.0,1626.74,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,1626.74,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,1631.73,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,1666.66,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,1671.65,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,13757.43,5.75,5.76,3.50
53936,0.72,Good,D,SI1,63.1,55.0,13757.43,5.69,5.75,3.61
53937,0.70,Very Good,D,SI1,62.8,60.0,13757.43,5.66,5.68,3.56
53938,0.86,Premium,H,SI2,61.0,58.0,13757.43,6.15,6.12,3.74
53939,0.75,Ideal,D,SI2,62.2,55.0,13757.43,5.83,5.87,3.64

<h4>Transformando os comprimentos X, Y e Z, que estão em mm, para nm:</h4>

In [5]:
dataframe2["x"] = dataframe2["x"] * 10**6
dataframe2["y"] = dataframe2["y"] * 10**6
dataframe2["z"] = dataframe2["z"] * 10**6
dataframe2

,carat,cut,color,clarity,depth,table,price,x,y,z
0,0.23,Ideal,E,SI2,61.5,55.0,1626.74,3950000.0,3980000.0,2430000.0
1,0.21,Premium,E,SI1,59.8,61.0,1626.74,3890000.0,3840000.0,2310000.0
2,0.23,Good,E,VS1,56.9,65.0,1631.73,4050000.0,4070000.0,2310000.0
3,0.29,Premium,I,VS2,62.4,58.0,1666.66,4200000.0,4230000.0,2630000.0
4,0.31,Good,J,SI2,63.3,58.0,1671.65,4340000.0,4350000.0,2750000.0
...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,13757.43,5750000.0,5760000.0,3500000.0
53936,0.72,Good,D,SI1,63.1,55.0,13757.43,5690000.0,5750000.0,3610000.0
53937,0.70,Very Good,D,SI1,62.8,60.0,13757.43,5660000.0,5680000.0,3560000.0
53938,0.86,Premium,H,SI2,61.0,58.0,13757.43,6150000.0,6120000.0,3740000.0
53939,0.75,Ideal,D,SI2,62.2,55.0,13757.43,5830000.0,5870000.0,3640000.0

<h2>Normalizações</h2>
<h4>Normalização do atributo carat pelo método padrão:</h4>
A `normalização padrão`, que consiste em alterar a média dos dados para zero e o desvio padrão dos dados para um, obtemos o seguinte resultado:

In [6]:
media = dataframe2['carat'].mean()
desvio_padrao = dataframe2['carat'].std()

dataframe2['Carat_zscore'] = (dataframe2['carat'] - media) / desvio_padrao

dataframe2

,carat,cut,color,clarity,depth,table,price,x,y,z,Carat_zscore
0,0.23,Ideal,E,SI2,61.5,55.0,1626.74,3950000.0,3980000.0,2430000.0,-1.198157
1,0.21,Premium,E,SI1,59.8,61.0,1626.74,3890000.0,3840000.0,2310000.0,-1.240350
2,0.23,Good,E,VS1,56.9,65.0,1631.73,4050000.0,4070000.0,2310000.0,-1.198157
3,0.29,Premium,I,VS2,62.4,58.0,1666.66,4200000.0,4230000.0,2630000.0,-1.071577
4,0.31,Good,J,SI2,63.3,58.0,1671.65,4340000.0,4350000.0,2750000.0,-1.029384
...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,13757.43,5750000.0,5760000.0,3500000.0,-0.164426
53936,0.72,Good,D,SI1,63.1,55.0,13757.43,5690000.0,5750000.0,3610000.0,-0.164426
53937,0.70,Very Good,D,SI1,62.8,60.0,13757.43,5660000.0,5680000.0,3560000.0,-0.206619
53938,0.86,Premium,H,SI2,61.0,58.0,13757.43,6150000.0,6120000.0,3740000.0,0.130926
53939,0.75,Ideal,D,SI2,62.2,55.0,13757.43,5830000.0,5870000.0,3640000.0,-0.101136

<h4>Normalização do atributo carat pelo método de máximo absoluto:</h4>
A <b>normalização pelo máximo absoluto</b> , que faz com que o valor máximo dos dados seja 1, obtemos o seguinte resultado:

In [7]:
carat_maximo = max(abs(dataframe2['carat']))

dataframe2['Carat_norm_max_abs'] = dataframe2['carat'] / carat_maximo

dataframe2

,carat,cut,color,clarity,depth,table,price,x,y,z,Carat_zscore,Carat_norm_max_abs
0,0.23,Ideal,E,SI2,61.5,55.0,1626.74,3950000.0,3980000.0,2430000.0,-1.198157,0.045908
1,0.21,Premium,E,SI1,59.8,61.0,1626.74,3890000.0,3840000.0,2310000.0,-1.240350,0.041916
2,0.23,Good,E,VS1,56.9,65.0,1631.73,4050000.0,4070000.0,2310000.0,-1.198157,0.045908
3,0.29,Premium,I,VS2,62.4,58.0,1666.66,4200000.0,4230000.0,2630000.0,-1.071577,0.057884
4,0.31,Good,J,SI2,63.3,58.0,1671.65,4340000.0,4350000.0,2750000.0,-1.029384,0.061876
...,...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,13757.43,5750000.0,5760000.0,3500000.0,-0.164426,0.143713
53936,0.72,Good,D,SI1,63.1,55.0,13757.43,5690000.0,5750000.0,3610000.0,-0.164426,0.143713
53937,0.70,Very Good,D,SI1,62.8,60.0,13757.43,5660000.0,5680000.0,3560000.0,-0.206619,0.139721
53938,0.86,Premium,H,SI2,61.0,58.0,13757.43,6150000.0,6120000.0,3740000.0,0.130926,0.171657
53939,0.75,Ideal,D,SI2,62.2,55.0,13757.43,5830000.0,5870000.0,3640000.0,-0.101136,0.149701

<h4>Normalização do atributo carat pelo método de mínimo e máximo:</h4>
A <b>normalização pelo mínimo e máximo</b>, que modifica os dados de forma que, após a transformação, os dados tenham valor mínimo de 0 e valor máximo de 1, obtemos o seguinte resultado:

In [8]:
maximo = dataframe2['carat'].max()
minimo = dataframe2['carat'].min()

dataframe2['Carat_norm_min_max'] = (dataframe2['carat'] - minimo) / (maximo - minimo)

dataframe2

,carat,cut,color,clarity,depth,table,price,x,y,z,Carat_zscore,Carat_norm_max_abs,Carat_norm_min_max
0,0.23,Ideal,E,SI2,61.5,55.0,1626.74,3950000.0,3980000.0,2430000.0,-1.198157,0.045908,0.006237
1,0.21,Premium,E,SI1,59.8,61.0,1626.74,3890000.0,3840000.0,2310000.0,-1.240350,0.041916,0.002079
2,0.23,Good,E,VS1,56.9,65.0,1631.73,4050000.0,4070000.0,2310000.0,-1.198157,0.045908,0.006237
3,0.29,Premium,I,VS2,62.4,58.0,1666.66,4200000.0,4230000.0,2630000.0,-1.071577,0.057884,0.018711
4,0.31,Good,J,SI2,63.3,58.0,1671.65,4340000.0,4350000.0,2750000.0,-1.029384,0.061876,0.022869
...,...,...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,13757.43,5750000.0,5760000.0,3500000.0,-0.164426,0.143713,0.108108
53936,0.72,Good,D,SI1,63.1,55.0,13757.43,5690000.0,5750000.0,3610000.0,-0.164426,0.143713,0.108108
53937,0.70,Very Good,D,SI1,62.8,60.0,13757.43,5660000.0,5680000.0,3560000.0,-0.206619,0.139721,0.103950
53938,0.86,Premium,H,SI2,61.0,58.0,13757.43,6150000.0,6120000.0,3740000.0,0.130926,0.171657,0.137214
53939,0.75,Ideal,D,SI2,62.2,55.0,13757.43,5830000.0,5870000.0,3640000.0,-0.101136,0.149701,0.114345

<h2>Utilizando o módulo scikit-learn! :D </h2>
Realizando conversão simbólico-numérico de diferentes maneiras com o scikit-learn:<br>
<h4>One-hot encoder no atributo color:</h4>

In [9]:
from sklearn.preprocessing import OneHotEncoder

x = dataframe2["color"].values.reshape(-1, 1)

encoder = OneHotEncoder(sparse=False)

encoder.fit(x)

colunas = encoder.categories_

dados_convertidos = encoder.transform(x)

idade_desnormalizada = encoder.inverse_transform(dados_convertidos)

for i, col in enumerate(colunas):
    dados = dados_convertidos[:,i]
    dataframe2[col] = dados

# print("Dados originais")
# print(x)
# print()

# print("Dados convertidos:")
# print(colunas)
# print(dados_convertidos)
# print()

# print("Dados desconvertidos:")
# print(idade_desnormalizada)
dataframe2

ValueError: Columns must be same length as key

<h4>Ordinal encoder no atributo color:</h4>

In [1]:
from sklearn.preprocessing import OrdinalEncoder

x = dataframe2["cut"].values.reshape(-1, 1)

ordem = [["Fair", "Good", "Very Good", "Premium", "Ideal"]]
encoder = OrdinalEncoder(categories=ordem)

encoder.fit(x)

dados_convertidos = encoder.transform(x)

idade_desnormalizada = encoder.inverse_transform(dados_convertidos)

# Add as modificações no dataframe
dataframe2["cut"] = dados_convertidos
dataframe2

NameError: name 'dataframe2' is not defined